results_dir: /tao-pt/results/check_onnx_b0

export:
  checkpoint: "/tao-pt/results/check_imagenet_mitb0/train/epoch_5.pth"
  onnx_file: "mitb0.onnx"
  verify: true

dataset:
  data:
    samples_per_gpu: 128
    workers_per_gpu: 8
    train:
      data_prefix: "/workspace/data/imagenet/train"
      pipeline:
        - type: RandomResizedCrop
          scale: 224
          backend: pillow
          interpolation: bicubic
        - type: RandomFlip
          prob: 0.5
          direction: horizontal
        - type: RandAugment
          policies: timm_increasing
          num_policies: 2
          total_level: 10
          magnitude_level: 9
          magnitude_std: 0.5
        - type: RandomErasing
          erase_prob: 0.25
          mode: rand
          min_area_ratio: 0.02
          max_area_ratio: 0.333333
          fill_color: 
            - 103.53
            - 116.28
            - 123.675
          fill_std:
            - 57.375
            - 57.12
            - 58.395
    val:
      data_prefix: /workspace/data/imagenet/val
    test:
      data_prefix: /workspace/data/imagenet/val
model:
  backbone:
    type: mit_b0
  head:
    type: TAOLinearClsHead
    in_channels: 256
    num_classes: 1000
    loss:
      type: CrossEntropyLoss
      loss_weight: 1.0
      use_soft: True
    topk: [1, 5]
  train_cfg:
    augments:
      - type: Mixup
        alpha: 0.8
      - type: CutMix
        alpha: 1.0
train:
  train_config:
    find_unused_parameters: True
    optimizer:
      type: AdamW
      lr: 5e-4
      weight_decay: 0.05
    # lr_config: [{type: 'LinearLR', by_epoch: True, begin: 0, end: 5, convert_to_iter_based: True}, {type: 'CosineAnnealingLR', T_max: 295, by_epoch: True, begin: 5, end: 300}]
    lr_config: {type: 'CosineAnnealingLR', T_max: 300, by_epoch: True, begin: 0, end: 300}
    runner:
      max_epochs: 300
    checkpoint_config:
      interval: 1
    logging:
      interval: 500
    evaluation:
      interval: 1
    custom_hooks:
      - type: "EMAHook"
        momentum: 0.0002
        priority: "ABOVE_NORMAL"
